name: Docker Image CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --tag $DOCKER_USERNAME/twoday-arcade:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
          docker push $DOCKER_USERNAME/twoday-arcade:latest
